# Configuration file for the microphone
tts:
  default_param:
    region_name: "eu-west-2"
    language: "en-US"
    outdir: "$(find harmoni_tts)/temp_data"
    wav_header_length: 24
    voice: "Amy"
