# This is a configuration file describing the id of the child of each repo
harmoni:
  bot: ["default"]
  tts: ["default"]
  #web: ["default"]
  #stt: ["default"]
  #face_detect: ["default"]
  hass: ["default"]
  pattern: ["default"]
hardware:
  #microphone: ["default"]
  #camera: ["default"]
  face: ["default"]
  speaker: ["default"]
  # gesture: ["default"]
hass:
  microphone: ["default"]
  stt: ["default"]
  bot: ["default"]
  tts: ["default"]
  face: ["default"]
  speaker: ["default"]
  hass: ["default"]
pattern:
  setup: ["default"]
  reverse_dialogue: ["default"]
  hass: ["default"]
