version: "3.7"

services:
  harmoni_full:
    container_name: harmoni_full
    build:
      context: .
      dockerfile: dockerfiles/harmoni/$ROS_DISTRO/full/dockerfile
      network: host
    image: harmoniteam/harmoni:$ROS_DISTRO-full
    init: true
    environment:
      DISPLAY: $DISPLAY
      QT_GRAPHICSSYSTEM: native
      ROS_DISTRO: $ROS_DISTRO
      ROS_MASTER_URI: https://172.18.3.4:11311
      IS_DOCKER_ENV: "true"
      ROS_HOSTNAME: harmoni_full
      CATKIN_WS: harmoni_catkin_ws
    privileged: true
    networks:
      ros_net:
        ipv4_address: 172.18.3.4
    hostname: harmoni_full
    ports:
      - "11312:11312"
      - "33691:33691"
      - "8081:8081"
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0
    volumes:
      - ../HARMONI/:/root/local_mount/HARMONI/
      # Configuration
      - ~/.aws:/root/.aws/
      - ~/.gcp/private-keys.json:/root/.gcp/private-keys.json
      - ~/.hass:/root/.hass/
      # Other
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /root/harmoni_catkin_ws/src/HARMONI
    command: tail  -f /dev/null

  harmoni_hardware:
    container_name: harmoni_hardware
    build:
      context: .
      dockerfile: dockerfiles/harmoni/$ROS_DISTRO/full/dockerfile
      network: host
    image: harmoniteam/harmoni:$ROS_DISTRO-full
    init: true
    environment:
      DISPLAY: $DISPLAY
      QT_GRAPHICSSYSTEM: native
      ROS_DISTRO: $ROS_DISTRO
      IS_DOCKER_ENV: "true"
      CATKIN_WS: harmoni_catkin_ws
      ROS_HOSTNAME: harmoni_hardware
      ROS_MASTER_URI: https://172.18.3.4:11311
    privileged: true
    networks:
      ros_net:
        ipv4_address: 172.18.3.5
    hostname: ros_hardware
    depends_on:
      - "harmoni_full"
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0
    volumes:
      - ../HARMONI/:/root/local_mount/HARMONI/
      # Configuration
      - ~/.aws:/root/.aws/
      - ~/.gcp/private-keys.json:/root/.gcp/private-keys.json
      # Other
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /root/harmoni_catkin_ws/src/HARMONI
    command: tail  -f /dev/null

networks:
  ros_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.3.0/24

volumes:
  wav2letter:
